import {DEV_URL, GOOGLE_MAP_API_KEY, LIVE_URL, SENTRY_URL} from '@env';

const isProduction = false;

const BASE_URL = isProduction ? LIVE_URL : DEV_URL;

export const ApiConstants = {
  BASE_URL,
  SENTRY_URL,
  GOOGLE_MAP_API_KEY,

  SEND_AUTH_OTP: `${BASE_URL}login/send_otp`,
  VERIFY_AUTH_OTP: `${BASE_URL}login/verify_otp`,
  REGISTER: `${BASE_URL}registers`,
  ROLES: `${BASE_URL}role_list`,
  REQUIREMENT_LIST: `${BASE_URL}requirment_list`,
  DEALER_COMPANY: `${BASE_URL}main_categories`,
  ADD_REVIEW: `${BASE_URL}review/add`,
  LOGOUT: `${BASE_URL}logout`,
  COUNTRIES: `${BASE_URL}country_list`,
  STATES: `${BASE_URL}states_list?id_country=`,
  CITY: `${BASE_URL}cities_list?id_state=`,
  CATEGORY: `${BASE_URL}category_list`,
  GET_MODEL: `${BASE_URL}model_list`,
  GET_TYPE_OF_MANUFACTURER: `${BASE_URL}manufacturer_list`,
  GET_PARTS: `${BASE_URL}parts_list`,
  GET_USER_PROFILE_POST: `${BASE_URL}get_by_user_id_and_type`,
  GET_PROFILE: `${BASE_URL}profile`,
  EDIT_PERSONAL_PROFILE: `${BASE_URL}update_profile`,
  UPDATE_JSON_FIELDS: `${BASE_URL}update_json_data_by_user_id`,
  GET_TERMS: `${BASE_URL}terms`,
  GET_PRIVACY: `${BASE_URL}privacy`,
  GET_FAQ: `${BASE_URL}faq_list`,
  CONTACT_US: `${BASE_URL}contactus/saves`,
  DELETE_ACCOUNT: `${BASE_URL}contactus/delete_account_request`,
  GET_DIRECTORY: `${BASE_URL}directory`,
  GET_DIRECTORY_DETAIL: `${BASE_URL}directory/get_by_id`,
  ADD_COMPANY_PDF: `${BASE_URL}add_business_pdf_and_names`,
  GET_COMPANY_PDF: `${BASE_URL}get_business_pdf_and_names`,
  DELETE_COMPANY_PDF: `${BASE_URL}delete_business_pdf_and_names`,
  GET_NOTIFICATION: `${BASE_URL}notification/get_all`,
  DELETE_NOTIFICATION: `${BASE_URL}notification/delete`,
  MARK_ALL_READ: `${BASE_URL}notification/mark_all_read`,
  MARK_INDIVIDUAL_READ: `${BASE_URL}notification/mark_read_by_id`,
  UNREAD_COUNT: `${BASE_URL}notification/unread_count`,
  UPDATE_PUSH_TOKEN: `${BASE_URL}notification/update_fcm_token`,
  SEND_CHAT_NOTIFICATIONS: `${BASE_URL}notification/send_chat_notification`,
  GET_WORKING_WITH: `${BASE_URL}get_working_with_by_user_id`,
  SEARCH_USERS: `${BASE_URL}get_username_search`,
  ADD_WORKING_WITH_MEMBER: `${BASE_URL}working_with_approval_add`,
  UPDATE_WORKING_WITH_REQUEST: `${BASE_URL}working_with_approval_request_by_id`,
  GET_HOME_LIKE_POST: `${BASE_URL}home_list/home_like_unlike`,
  GET_BUYER_LIKE_POST: `${BASE_URL}buyer_requirment/buyer_like_unlike`,
  GET_SELLER_LIKE_POST: `${BASE_URL}seller_requirment/seller_like_unlike`,
  GET_FAV_POSTS: `${BASE_URL}fav/get_by_type`,
  HOME_GET: `${BASE_URL}home_list_get`,
  GET_BUYER_POSTS: `${BASE_URL}buyer_list_get`,
  GET_SELLER_POSTS: `${BASE_URL}seller_list_get`,
  ADD_HOME_POST: `${BASE_URL}home_list_add`,
  ADD_BUYER_POST: `${BASE_URL}buyer/add`,
  ADD_SELLER_POST: `${BASE_URL}seller/add`,
  DELETE_POST_IMAGE: `${BASE_URL}delete_by_id_image`,
  DELETE_POST: `${BASE_URL}delete_by_id_post`,
  GET_POST_COMMENTS: `${BASE_URL}comments/get_comments`,
  ADD_POST_COMMENT: `${BASE_URL}comments/add_update_comments`,
  DELETE_POST_COMMENT: `${BASE_URL}comments/delete_comments`,
  TOGGLE_POST_COMMENT_LIKE: `${BASE_URL}comments/like_unlike_comments`,
  TOGGLE_POST_LIKE: `${BASE_URL}comments/like_unlike_likes`,
  GET_FILTER: `${BASE_URL}get_filter_data`,
};
